server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bluesky
    password: bluesky
    url: jdbc:mysql://datahelper.mysql:3306/datahelper?allowMultiQueries=true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: GMT+8

logging:
  level:
    root: info
    me:
      ihint:
        datahelper: debug
